FirstPro/CoffeeShop/urls.py
from django.contrib import admin
from django.urls import include
from django.conf.urls.static import static
from CoffeeShop import settings
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('cfuser.urls')),
    url(r'^board/', include('cfboard.urls')),
    url(r'^coffee/', include('cfproduct.urls')),
    url(r'^buy/', include('cfbuy.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FirstPro/cfboard/urls.py
from django.conf.urls import url
from django.urls import include

from cfboard.views import *

app_name = 'cfboard'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^(?P<pk>\d{1})/$',boards, name='boards'),
    url(r'^(?P<pk>\d{1})/detail/(?P<id>\d+)/$',board_detail, name='board_detail'),
    url(r'^(?P<pk>\d{1})/detail/(?P<id>\d+)/comment/$',comment_write, name='board_comment'),
    url(r'^(?P<pk>\d{1})/create/$',board_write, name='board_create'),
    
]

FirstPro/cfbuy/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from cfbuy.views import *

app_name = 'cfbuy'

urlpatterns = [
    # url(r'^test/$',TemplateView.as_view(template_name='cfproduct/test.html'),name='test'),
    url(r'^detail/$',TemplateView.as_view(template_name='cfbuy/_detail.html'),name='detail'),
    url(r'^cart/$',TemplateView.as_view(template_name='cfbuy/cart.html'),name='cart'),
    url(r'^buy_page/$',TemplateView.as_view(template_name='cfbuy/buy_page.html'),name='buy_page'),
    url(r'^order/$',order_list,name='order_list'),
    url(r'^complete/$',buy_complete,name='buy_complete'),
    url(r'^graph/$',show_graph,name='graph'),
    url(r'^kakao/$',kakaopay,name='kakao_pay'),
    url(r'^approve/$',approval,name='approve'),
    url(r'^cancel/$',TemplateView.as_view(template_name='cfbuy/payCancel.html'),name='cancel'),
    url(r'^fail/$',TemplateView.as_view(template_name='cfbuy/payFail.html'),name='fail'),
]

FirstPro/cfproduct/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from cfproduct.views import *

app_name = 'cfproduct'

urlpatterns = [
    # url(r'^test/$',TemplateView.as_view(template_name='cfproduct/test.html'),name='test'),
    url(r'^$', index, name='index'),
    url(r'^(?P<pk>\d{1})/$',coffee, name='coffee'),
    url(r'^detail/(?P<id>\d{1,3})/$',product_detail, name='coffee_detail'),
    url(r'^detail/(?P<id>\d{1,3})/comment$',product_comment, name='coffee_comment'),
    url(r'^buy/detail/$',buy_detail, name='buy_detail'),
  
    url(r'^detail/$',TemplateView.as_view(template_name='cfproduct/product_detail.html'),name='detail'),
    url(r'^cart/$',TemplateView.as_view(template_name='cfproduct/cart.html'),name='cart'),
    url(r'^buy_page/$',TemplateView.as_view(template_name='cfproduct/buy_page.html'),name='buy_page'),
    url(r'^order/$',TemplateView.as_view(template_name='cfproduct/order.html'),name='order'),
]

FirstPro/cfuser/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from cfuser.views import *
from cfbuy.views import show_graph
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cfuser'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^graph/$', show_graph, name='graph'),
    url(r'^cart/$',cart,name='cart'),
    url(r'^about/$',TemplateView.as_view(template_name='map.html'),name='about'),
    url(r'^profile/$',profile,name='profile'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FirstPro/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>LOVE(CAFE)_CoffeeShop</title>
  

  <!-- Bootstrap core CSS -->

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery-3.1.1.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  


  <!-- Custom fonts for this template -->
  <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">


  <!-- Custom styles for this template -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link href="{% static 'css/business-casual.min.css' %}" rel="stylesheet">


  {% block header %}
  {% endblock %}

</head>
<style>

  .site-heading-upper{
    color: #e6a958;
  }
  .dropdown-menu{
    background-color: #e6a958;
    background-color: rgba(255, 255, 255, 0);
  }
  li > a{
    color: #e6a958;
    font-size: 14px;
  }
  li > a:hover{
    color: #ce8f3d;
  }
  #site-heading-link{
    text-decoration: none;
    color:white;
    font-size: 65px;
  }


</style>

<body>

  <h1 class="site-heading text-center text-white d-none d-lg-block">
    <span class="site-heading-upper md-5">LOVE(CAFE)</span>
    <span class="site-heading-lower"><a href="{% url 'cfuser:index' %}" id="site-heading-link">Coffee & Beans</a></span>
  </h1>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark px-5" id="mainNav">
    <div class="container">
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'cfuser:index' %}">LOVE(CAFE)</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item active px-5">
            <a class="nav-link text-uppercase text-expanded font-weight-bold" href="{% url 'cfuser:index' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item px-5">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'cfuser:about' %}">About</a>
          </li>
          <li>
            <div class="dropdown nav-item px-5">
              <a class="dropdown-toggle nav-link text-expanded font-weight-bold btn-block" data-toggle="dropdown"aria-expanded="false" href="#">SHOP</a>
              <ul class="dropdown-menu font-weight-bold text-center" role="menu" aria-labelledby="dLabel">           
                <li><a href="{% url 'cfproduct:coffee' 1 %}">SINGLE ORIGINS</a></li>
                <li><a href="{% url 'cfproduct:coffee' 2 %}">BLEND</a></li>
                <li><a href="{% url 'cfproduct:coffee' 3 %}">EASY COFFEE</a></li>
              </ul>
            </div>   
          </li>
          <li>
            <div class="dropdown nav-item px-5">
              <a class="dropdown-toggle nav-link text-expanded font-weight-bold btn-block" data-toggle="dropdown" href="#">BOARD</a>
              <ul class="dropdown-menu font-weight-bold text-center" role="menu" aria-labelledby="dLabel">           
                <li><a href="{% url 'cfboard:boards' 1 %}">자주 묻는 질문</a></li>
                <li><a href="{% url 'cfboard:boards' 2 %}">도매 납품 상담</a></li>
                <li><a href="{% url 'cfboard:boards' 3 %}">Q & A</a></li>
              </ul>
            </div>   
          </li>
          
          {% if request.session.user %}
          <li>
            <div class="dropdown nav-item px-5">
              <a class="dropdown-toggle nav-link text-expanded font-weight-bold btn-block" data-toggle="dropdown" href="#">MYPAGE</a>
              <ul class="dropdown-menu font-weight-bold text-center" role="menu" aria-labelledby="dLabel">           
                <li><a href="{% url 'cfuser:profile' %}">PROFILE</a></li>
                <li><a href="{% url 'cfuser:cart' %}">CART</a></li>
                <li><a href="{% url 'cfbuy:order_list' %}">ORDER</a></li>
                {% if request.session.mode == 'admin' %}
                  <li><a href="{% url 'cfuser:graph' %}">GRAPH</a></li>
                {% endif %}
              </ul>
            </div>   
          </li>
          <li class="nav-item px-5">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'cfuser:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item px-5">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'cfuser:login' %}">Login</a>
          </li>
  

          {% endif %}
          
         
          
        </ul>
      </div>
    </div>
  </nav>



  <div class="container">
    {% block contents %}
    {% endblock %}
  </div>

  <footer class="footer text-faded text-center py-5">
    <div class="container">
      <p class="m-0 small">Copyright &copy; Your Website 2021</p>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstarp.js' %}"></script>
  

</html>

FirstPro/templates/graph.html
{% extends 'base.html' %}



{% block contents %}

<style>
    #chart_div{
        margin: 40px 0 50px 20px;
    }
    .btn{
        width: 150px;
        height: 40px;
        margin: 80px 0 0 30px;
        text-decoration: none;
        background-color: #e6a958;
        color: #fff;
    }
    .btn:hover{
        background-color: #d3841c;
    }

   
</style>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<script type="text/javascript">
    var sold_cf = JSON.parse("{{ sold_cf|escapejs }}");
    var names = JSON.parse("{{ names|escapejs }}");
    var name_list = ["SINGLE ORIGINS", "BLEND", "EASY COFFEE"];
    var idx = 0;
    console.log(sold_cf);
    console.log(names);
    google.charts.load('current', {'packages':['corechart']}).then(function(){
        
    $("#btn-1").click(function(){
        idx = 0;
        var chart_data =[];
        var col = ['Month'];
        console.log(names["SINGLE ORIGIN"]);
        for(name in names[name_list[idx]])
        {
            col.push(names[name_list[idx]][name]);
        }
        chart_data.push(col);
        for(cf in sold_cf[name_list[idx]])
        {
            var row = [cf];
            for(quan in sold_cf[name_list[idx]][cf])
            {
                row.push(sold_cf[name_list[idx]][cf][quan]);
            }
            chart_data.push(row);
        }
        var data = google.visualization.arrayToDataTable(chart_data);

        var options = {
            title : '월간 커피 판매량(SINGLE ORIGINS)',
            vAxis: {title: '커피'},
            hAxis: {title: 'Month'},
            seriesType: 'bars',
            series: {8: {type: 'line'}}
        };

        var chart = new google.visualization.ComboChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    })
    $("#btn-2").click(function(){
        idx = 1;
        var chart_data =[];
        var col = ['Month'];
        for(name in names[name_list[idx]])
        {
            col.push(names[name_list[idx]][name]);
        }
        chart_data.push(col);
        for(cf in sold_cf[name_list[idx]])
        {
            var row = [cf];
            for(quan in sold_cf[name_list[idx]][cf])
            {
                row.push(sold_cf[name_list[idx]][cf][quan]);
            }
            chart_data.push(row);
        }
        var data = google.visualization.arrayToDataTable(chart_data);

        var options = {
            title : '월간 커피 판매량(BLEND)',
            vAxis: {title: '커피'},
            hAxis: {title: 'Month'},
            seriesType: 'bars',
            series: {8: {type: 'line'}}
        };

        var chart = new google.visualization.ComboChart(document.getElementById('chart_div'));
        chart.draw(data, options);
        
    })
    $("#btn-3").click(function(){
        idx = 2;
        var chart_data =[];
        var col = ['Month'];
        for(name in names[name_list[idx]])
        {
            col.push(names[name_list[idx]][name]);
        }
        chart_data.push(col);
        for(cf in sold_cf[name_list[idx]])
        {
            var row = [cf];
            for(quan in sold_cf[name_list[idx]][cf])
            {
                row.push(sold_cf[name_list[idx]][cf][quan]);
            }
            chart_data.push(row);
        }
        var data = google.visualization.arrayToDataTable(chart_data);

        var options = {
            title : '월간 커피 판매량(EASY COFFEE)',
            vAxis: {title: '커피'},
            hAxis: {title: 'Month'},
            seriesType: 'bars',
            series: {8: {type: 'line'}}
        };

        var chart = new google.visualization.ComboChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    })
});
</script>

<input class="btn" id="btn-1" type="button" value="SINGLE ORIGINS" />
<input class="btn" id="btn-2" type="button" value="BLEND" />
<input class="btn" id="btn-3" type="button" value="EASY COFFEE" />

<div id="chart_div" style="width: 1200px; height: 800px;"></div>



{% endblock %}



  

FirstPro/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block contents %}

  <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" style="width: 1000px; height: 600px" src="{% static 'img/main-frame.jpg' %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4">
            <span class="section-heading-upper">LOVE COFFEE</span>
            <span class="section-heading-lower">ENJOY DRINKING</span>
          </h2>
          <p class="mb-3">Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs. Love does not delight in evil but rejoices with the truth. It always protects, always trusts, always hopes, always perseveres.

          </p>
        </div>
      </div>
    </div>
  </section>

  <section class="page-section cta">
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <div class="cta-inner text-center rounded">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">Our Promise</span>
              <span class="section-heading-lower">To You</span>
            </h2>
            <p class="mb-0">When you walk into our shop to start your day, we are dedicated to providing you with friendly service, a welcoming atmosphere, and above all else, excellent products made with the highest quality ingredients. If you are not satisfied, please let us know and we will do whatever we can to make things right!</p>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

FirstPro/templates/map.html
{% extends 'base.html' %}

{% block header %}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=a188d022f9e19591c7c1200b7aca5610"></script>

<script>
    // $(document).ready(function(){
    //     var container = document.getElementById('map'); //지도를 담을 영역의 DOM 레퍼런스
    //     var options = { //지도를 생성할 때 필요한 기본 옵션
    //         center: new kakao.maps.LatLng(37.557307, 126.924318), //지도의 중심좌표.
    //         level: 3 //지도의 레벨(확대, 축소 정도)
    //     };
        
    //     var map = new kakao.maps.Map(container, options); //지도 생성 및 객체 리턴
    // });

    $(document).ready(function(){
        var mapContainer = document.getElementById('map'), // 지도를 표시할 div 
        mapOption = { 
            center: new kakao.maps.LatLng(37.557112, 126.923904), // 지도의 중심좌표
            level: 3 // 지도의 확대 레벨
        };

        var map = new kakao.maps.Map(mapContainer, mapOption); // 지도를 생성합니다
        
        // 마커를 표시할 위치입니다 
        var position =  new kakao.maps.LatLng(37.557112, 126.923904);

        // 마커를 생성합니다
        var marker = new kakao.maps.Marker({
            position: position,
            clickable: true // 마커를 클릭했을 때 지도의 클릭 이벤트가 발생하지 않도록 설정합니다
        });

        // 아래 코드는 위의 마커를 생성하는 코드에서 clickable: true 와 같이
        // 마커를 클릭했을 때 지도의 클릭 이벤트가 발생하지 않도록 설정합니다
        // marker.setClickable(true);

        // 마커를 지도에 표시합니다.
        marker.setMap(map);

        // 마커를 클릭했을 때 마커 위에 표시할 인포윈도우를 생성합니다
        var iwContent = '<div style="padding:5px;">LoveCafe!</div><div style="padding:5px;">LoveCafe! <br><a href="https://map.kakao.com/link/map/LoveCafe!,37.557112, 126.923904" style="color:blue" target="_blank">큰지도보기</a> <a href="https://map.kakao.com/link/to/LoveCafe!,37.557112, 126.923904" style="color:blue" target="_blank">길찾기</a></div>', // 인포윈도우에 표출될 내용으로 HTML 문자열이나 document element가 가능합니다
            iwPosition = new kakao.maps.LatLng(37.557112, 126.923904); //인포윈도우 표시 위치입니다
        // var iwContent = '<div style="padding:5px;">LoveCafe!</div>', // 인포윈도우에 표출될 내용으로 HTML 문자열이나 document element가 가능합니다
            iwRemoveable = true; // removeable 속성을 ture 로 설정하면 인포윈도우를 닫을 수 있는 x버튼이 표시됩니다

        // 인포윈도우를 생성합니다
        var infowindow = new kakao.maps.InfoWindow({
            content : iwContent,
            removable : iwRemoveable
        });

        // 마커에 클릭이벤트를 등록합니다
        kakao.maps.event.addListener(marker, 'click', function() {
            // 마커 위에 인포윈도우를 표시합니다
            infowindow.open(map, marker);  
        });
    });
</script>
<style>
	#map-header{
		margin: 80px 0 50px 0;
		text-align: center;
		color:#e6a958
	}
	#map{
		margin: 0 auto;
		margin-bottom: 50px;
		width: 1000px;
		height: 500px;
	}
	.map-detail{
		margin: 0 auto;
        margin-bottom: 30px;
		width: 1000px;
		height: 300px;
		font-size: 18px;
		color: white;
	}
    #id{
        margin: 0 auto;
    }
</style>
{% endblock %}


{% block contents %}

<h1 id="map-header">찾아오시는 길</h1>
<div class="map-detail">
	<br>
	<p>대중교통 : 지하철 2호선 타고 홍대입구역에서 하차 2번출구 방면 50m</p>
	<p>자가 : 주차장이 협소하니 대중교통이나 근처 공용주차장을 이용해주시기 바랍니다.</p>
	<p>주소 : 서울 마포구 양화로 165 상진빌딩 1층</p>
	<p>TEL : 02-888-8888</p>
	<P>월 - 금 : 8am-9pm</P>
	<p>토, 일 및 공휴일 : 10am-8pm</p>
</div>
<div id="map"></div>

{% endblock %}