FirstPro/CoffeeShop/urls.py
from django.contrib import admin
from django.urls import include
from django.conf.urls.static import static
from CoffeeShop import settings
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('cfuser.urls')),
    url(r'^board/', include('cfboard.urls')),
    url(r'^coffee/', include('cfproduct.urls')),
    url(r'^buy/', include('cfbuy.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FirstPro/cfboard/urls.py
from django.conf.urls import url
from django.urls import include

from cfboard.views import *

app_name = 'cfboard'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^(?P<pk>\d{1})/$',boards, name='boards'),
    url(r'^(?P<pk>\d{1})/detail/(?P<id>\d+)/$',board_detail, name='board_detail'),
    url(r'^(?P<pk>\d{1})/detail/(?P<id>\d+)/comment/$',comment_write, name='board_comment'),
    url(r'^(?P<pk>\d{1})/create/$',board_write, name='board_create'),
    
]

FirstPro/cfbuy/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from cfbuy.views import *

app_name = 'cfbuy'

urlpatterns = [
    # url(r'^test/$',TemplateView.as_view(template_name='cfproduct/test.html'),name='test'),
    url(r'^detail/$',TemplateView.as_view(template_name='cfbuy/_detail.html'),name='detail'),
    url(r'^cart/$',TemplateView.as_view(template_name='cfbuy/cart.html'),name='cart'),
    url(r'^buy_page/$',TemplateView.as_view(template_name='cfbuy/buy_page.html'),name='buy_page'),
    url(r'^order/$',order_list,name='order_list'),
    url(r'^complete/$',buy_complete,name='buy_complete'),
    url(r'^graph/$',show_graph,name='graph'),
    url(r'^kakao/$',kakaopay,name='kakao_pay'),
    url(r'^approve/$',approval,name='approve'),
    url(r'^cancel/$',TemplateView.as_view(template_name='cfbuy/payCancel.html'),name='cancel'),
    url(r'^fail/$',TemplateView.as_view(template_name='cfbuy/payFail.html'),name='fail'),
]

FirstPro/cfboard/models.py
from django.db import models

DISCLOSURE_CHOICES = (
    (0, 'private'),
    (1, 'public')
)

# Create your models here.
class Cfboard(models.Model):
    title = models.CharField(max_length=50,verbose_name='제목')
    contents = models.TextField(verbose_name='내용')
    hits = models.IntegerField(default=0, verbose_name='조회수')
    writer = models.ForeignKey('cfuser.Cfuser', on_delete=models.CASCADE,
                               verbose_name='작성자')
    boardname = models.ForeignKey('cfboard.Boardcode', on_delete=models.CASCADE,verbose_name='보드종류')
    catename = models.ForeignKey('cfboard.Boardcate', on_delete=models.CASCADE,verbose_name='카테고리')
    disclosure = models.SmallIntegerField(choices=DISCLOSURE_CHOICES)
    registered_dttm = models.DateTimeField(auto_now_add=True,
                                           verbose_name='등록시간')
    def __str__(self):
        return self.title

    class Meta:
        db_table = 'coffeeshop board'
        verbose_name = '게시판'
        verbose_name_plural = '게시판'

class Boardcode(models.Model):
    boardname = models.CharField(max_length=50)
    
    def __str__(self):
        return self.boardname
    
    class Meta:
        db_table = 'board name'
        verbose_name = '게시판종류'
        verbose_name_plural = '게시판종류'

class Boardcate(models.Model):
    catename = models.CharField(max_length=50)

    def __str__(self):
        return self.catename
    
    class Meta:
        db_table = 'board category'
        verbose_name = '카테고리'
        verbose_name_plural = '카테고리'

class Boardcomment(models.Model):
    board = models.ForeignKey('cfboard.Cfboard', on_delete=models.CASCADE,verbose_name='게시글')
    user = models.ForeignKey('cfuser.Cfuser', on_delete=models.CASCADE, verbose_name='작성자')
    contents = models.TextField(verbose_name='내용')
    

    def __str__(self):
        return self.board.title
    
    class Meta:
        db_table = 'board comment'
        verbose_name = '댓글'
        verbose_name_plural = '댓글'

FirstPro/cfboard/views.py
from django.shortcuts import render, reverse, redirect
from django.views.generic import ListView, TemplateView
from django.core.paginator import Paginator

from cfboard.models import *
from cfuser.models import Cfuser

# Create your views here.
def index(request):
    return render(request, 'board.html')

def board_detail(request, pk, id):
    boardname = Boardcode.objects.get(id=pk)
    res_data = {'boardname' : boardname, 'pk' : pk, 'id' : id}
    try:
        board = Cfboard.objects.get(id=id)
        user = Cfuser.objects.get(id=board.writer.id)
        res_data['user'] = user
        res_data['board'] = board
        comments = Boardcomment.objects.filter(board=board)
        res_data['comments'] = comments
        board.hits = board.hits+1
        board.save()
    except Cfboard.DoesNotExist:
        raise Http404('게시글을 찾을 수 없습니다')


    return render(request, 'cfboard/cfboard_detail.html', res_data)
    

def boards(request, pk):
    res_data = {'pk' : pk}
    boardname = Boardcode.objects.get(id=pk)
    if request.method=="POST":
        delete_id = request.POST.get('delete')
        delete_board = Cfboard.objects.filter(id=delete_id)
        if delete_board:
            delete_board.delete()
    try:
        board_lists = Cfboard.objects.filter(boardname=boardname).order_by('id')
        board_list = []
        for idx, board in enumerate(board_lists):
            board_list.append([idx+1,board])
        board_list.reverse()
        res_data['boardname'] = boardname
        res_data['boards'] = board_list
        paginator = Paginator(board_list, 8) # Show 25 contacts per page.
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        res_data['page_obj'] = page_obj
        
    except Cfboard.DoesNotExist:
        raise Http404('게시글을 찾을 수 없습니다')

    return render(request, 'cfboard/cfboard.html', res_data)

def board_write(request, pk):
    errors = []
    boardname = Boardcode.objects.get(id=pk)
    catelist = Boardcate.objects.all()
    print('here',request)
    if request.method == 'POST':
        title = request.POST.get('title', '').strip()
        contents = request.POST.get('contents', '').strip()
        category = request.POST.get('category')
        disclosure = request.POST.get('disclosure')

        if not title:
            errors.append('제목을 입력해주세요.')

        if not contents:
            errors.append('내용을 입력해주세요.')

        if not errors and 'user' in request.session:
            user = Cfuser.objects.get(email=request.session['user'])
            catename = Boardcate.objects.get(id=category)
            
            cfboard = Cfboard.objects.create(writer=user, title=title, contents=contents, catename=catename, boardname=boardname, hits=0, disclosure=disclosure)

            return redirect(reverse('cfboard:boards', kwargs={'pk': pk}))
    

    return render(request, 'cfboard/cfboard_write.html', {'errors':errors, 'pk':pk, 'catelist':catelist})


def comment_write(request, pk, id):
    errors = []
    if request.method == "POST":
        user = Cfuser.objects.get(email=request.session['user'])
        board = Cfboard.objects.get(id=id)
        contents = request.POST.get('contents')

        if not contents:
            errors.append('댓글을 입력해주세요.')

        if not errors:
            comment = Boardcomment.objects.create(board=board, user=user, contents=contents)
            return redirect(reverse('cfboard:board_detail', kwargs={'pk': pk, 'id' : id}))

    return redirect(reverse('cfboard:board_detail', kwargs={'pk': pk, 'id' : id}))
    # return render(request, 'cfboard/cfboard_detail.html', {'board' : board, 'pk' : pk, 'id' : id,  'errors':errors})

FirstPro/templates/cfboard/cfboard.html
{% extends "base.html" %}

{% block header %}
<style>
  h1{
    margin: 105px 0 70px 0;
    color: #e6a756;
    text-align: center;
    font-size: 1.5em;
  }
  .table{
    font-weight: bolder;
    margin-bottom: 80px;
    background-color: #e6a756;
    color: black;
    border-radius: 8px;
    opacity: 0.7;
  }
  tr{
    font-size: 16px;
  }
  .btn{
    background-color:#e6a756 ;
    color: black;
    opacity: 0.7;
  }
  .btn:hover{
    background-color: #ce8f3d;
  }
  #title-link{
    color: black;
  }
  #btn-write{
    color: black;
  }
  .pagination{
    margin-top: 100px;
  }
  span{
    color: #ce8f3d;
  }
  span > a{
    color: #ce8f3d;
  }

</style>

{% endblock %}

{% block contents %}



<table class="table table-hover">
  <h1>{{ boardname }}</h1>
  {% if boards %}
    <thead class="thead-light">
      <tr>
        <th scope="col">번호</th>
        <th scope="col">카테고리</th>
        <th scope="col">제목</th>
        <th scope="col">작성자</th>
        <th scope="col">작성일</th>
        <th scope="col">조회</th>
      </tr>
    </thead>
    <tbody>
      {% for board in page_obj %}
      <tr>
        <th scope="row">{{ board.0 }}</th>
        <td>{{ board.1.catename }}</td>
        <td><a href="{% url 'cfboard:board_detail' pk board.1.id %}" id="title-link">{{ board.1.title }}</a></td>
        <td>{{ board.1.writer }}</td>
        <td>{{ board.1.registered_dttm }}</td>
        <td>{{ board.1.hits }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}
  
  {% if request.session.user %}
    {% if pk == '1' %}
      {% if request.session.mode == 'admin' %}
      <div class="form-row float-right">
        <button type="button" class="btn"><a href="{% url 'cfboard:board_create' pk %}" id="btn-write">글쓰기</a></button>
      </div>
      {% endif %}
    {% else %}
      <div class="form-row float-right">
        <button type="button" class="btn"><a href="{% url 'cfboard:board_create' pk %}" id="btn-write">글쓰기</a></button>
      </div>
    {% endif %}
  {% endif %}

  <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
  </div>

{% endblock %}

FirstPro/templates/cfboard/cfboard_detail.html
{% extends 'base.html' %}

{% block header %}

<style>
  h2{
    margin: 90px 0 25px 0;
    text-align: center;
    font-size: 20px;
    color: #e6a756;
  }
  .media-header{
    background-color: #e6a756;
    border-top-right-radius: 10px;
    border-top-left-radius: 10px;
  }
  h4{
    color: black;
    text-align: center;
  }

  h3{
    margin-top: 50px;
    color: black;
  }
  .media-body{
    margin: 40px 0 40px 0;
    background-color: white;
    border: 2px solid black;
    border-radius: 10px;
    opacity: 0.8;;
  }
  span{
    font-size: 15px;
  }
  p{
    font-size: 15px;
    font-weight: bolder;
  }
  .reply-form {
    opacity: 0.8;
    margin-top: 40px;
    padding: 37px;
    width: 1000px;
  }

  .textInput {
      border-top-left-radius: 10px;
      border-bottom-left-radius: 10px;
      width: 500px;
      height: 45px;
      margin: 0 !important;
  }
  .textInput:focus {
      box-shadow: none;
      outline: none
  }
  .commentBox ul .profileBox {
      width: 70px;
      height: 70px;
      border-radius: 50%;
      display: inline-flex;
      justify-content: center;
      align-items: center;
      background-color: #002247;
      color: rgb(93, 95, 95);
      font-weight: 700;
  }
  .commentBox ul li .profileBox {
      background-color: #222;
  }

  .profileText {
      border-radius: 7px;
      padding: 10px;
      position: relative;
      background-color: #e0efff;
      display: inline-block;
      margin-left: 15px;
      width: 50%;
  }
  .profileText::before {
      content: '';
      position: absolute;
      left: -9px;
      top: 50%;
      transform: translateY(-50%);
      width: 0px;
      height: 0px;
      border-top: 10px solid transparent;
      border-bottom: 10px solid transparent;
      border-right: 10px solid #e0efff;
      z-index: 1;
  }
  .commentBox{
    margin: 60px 0 0 40px;
  }
  .commentBox ul li {
      display: flex;
      align-items: center;
  }
  .commentBox ul ol .profileText::before {
      left: unset;
      right: -9px;
      transform: translateY(-50%) rotate(175deg);
  }
  .commentBox ul ol .profileText {
      text-align: right;
  }
  .commentBox ul li .profileText {
    text-align: left;
  }
  div#div_id_username {
      margin-top: 2%;
  }
  .commentBox ul .profileText {
      margin-right: 15px
  }
  .commentBox ul ol{
      text-align: right;
      margin: 20px 0;
      justify-content: right;
  }
  .commentBox ul li{
    text-align: left;
    margin: 20px 0;
    justify-content: left;
  }
  .btn{
    background-color: #e6a756;
  }

</style>

<script>
  $(document).ready(function(){
    var elem = document.getElementById('contents')
    elem.innerHTML = elem.innerText;
  });  
</script>
{% endblock %}

{% block contents %}

{% if errors %}
      <script>
        alert('빈칸을 다 채워주세요!');
      </script>
{% endif %}
<h2>{{ boardname }}</h2>


<div class="container">
  <div class="well">
      <div class="media-body">
        <div class="media-header">
        <br>

        <h4 id="media-heading">{{ board.title }}</h4>
        <p class="text-right" style="padding: 0 10px;">작성자 : {{ board.writer }}</p>
      </div>
          <p id='contents' style="padding: 0 10px;">
            {{ board.contents }}
          </p>
          <hr/>
          <ul class="list-inline list-unstyled" style="padding: 0 10px;">
            <li><span><i class="glyphicon glyphicon-calendar"></i> 작성일 : {{ board.registered_dttm }} </span></li>
            <li><span><i class="glyphicon glyphicon-calendar"></i> 조회수 : {{ board.hits }}</span></li>         
			    </ul>
      </div>
  </div>

  <a class="btn btn-primary float-right" href="{% url 'cfboard:boards' pk %}" role="button">목록</a>
  <form action="{% url 'cfboard:boards' pk %}" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn float-right" style="background-color: gray; margin-right: 5px;" name="delete" value='{{ id }}' role="button">삭제</button>
  </form>
</div>


<div class="container my-2">
  <div class="row mt-4">
    <div class="col-md-9">
          {% if comments %}
              <div class="commentBox">
                  <ul class="list-unstyled">
                      {% for comment in comments %}
                        {% if comment.user == user %}
                        
                          <li><span class="profileBox" style="background: no-repeat center/140% url('{{ comment.user.image.url }}');">{{ comment.user }}</span><span class="profileText">{{ comment.contents }}</span></li>
                        {% else%}
                          <ol><span class="profileText">{{ comment.contents }}</span><span class="profileBox" style="background: no-repeat center/140% url('{{ comment.user.image.url }}');">{{ comment.user }}</span></ol>
                        {% endif %}
                      {% endfor %}
                  </ul>
              </div>
          {% endif %}
          <form class="reply-form" method="post" action="{% url 'cfboard:board_comment' pk id %}">
            {% csrf_token %}
              <div id="div_id_username" class="form-group required">
                  <div class="controls form-group d-flex w-100 ">
                      <input class="input-md  textinput textInput form-control" id="id_username" name='contents' placeholder="Write your review" type="text" />
                      <button type="submit" class="btn border-radius-0  m-0 w-25">POST</button>
                  </div>
              </div>
          </form>
    </div>
  </div>
</div>

{% endblock %}

FirstPro/templates/cfboard/cfboard_write.html
{% extends 'base.html' %}

{% block header %}

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-bs4.min.js"></script>

{% endblock %}


{% block contents %}
    <style>
      label{
        color: #e6a756;
        font-size: 20px;
        margin: 10px;
      }
      input{
        border-radius: 4px;
        display: block;
        width: 400px;
      }
      .title-label{
        display: block;
        width: 100%;
      }
      #btn-save:hover{
        background-color: rgb(196, 133, 18);
      }
      #btn-save{
        background-color: #e6a756;
      }
      #cancel-btn{
        color: black;
      }
    </style>

    {% if errors %}
      <script>
        alert('빈칸을 다 채워주세요!');
      </script>
    {% endif %}


<div class="form-group">
  
  <form method="post" action="{% url 'cfboard:board_create' pk %}">
    {% csrf_token %}  
  <label>제목</label>
  <input type="text" name="title" placeholder="제목을 입력해주세요.">
  
  <label>내용</label>
  <textarea id="summernote" class="form-control" name="contents">
   {{ form.content.value|default_if_none:'' }}
  </textarea>
  <hr>
  <select class="form-select form-select-sm mb-3" style="width: 200px" aria-label=".form-select-lg example" name="category">
    {% for c in catelist %}
      <option value="{{ c.id }}">{{ c }}</option>
    {% endfor %}
  </select>
  <select class="form-select form-select-sm" style="width: 200px" aria-label=".form-select-sm example" name="disclosure">
    <option value="1">공개</option>
    <option value="2">비공개</option>
  </select>
  <div class="write-btn" align="right">
    <button type="button" class="btn btn-secondary btn-sm"><a href="{% url 'cfboard:boards' pk %}" id="cancel-btn">취소</a></button>
    <button type="submit" class="btn btn-sm" id="btn-save">저장</button>
    </div>
  </form>
</div>

<script>
    $('#summernote').summernote({
      placeholder: '내용을 입력하세요',
      tabsize: 2,
      height: 300
    });
</script>


{% endblock %}

FirstPro/templates/cfboard/ori_cfboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if boards %}
    <h2>{{ boardname }}</h2>
       <ul class="list-group">
            {% for board in boards %}
                <li class="list-group-item col-md-6">
                    <a href="{% url 'cfboard:board_detail' pk board.id %}">{{ board.title }}</a> 
                    <span>{{ board.writer }}</span>
                    <span>{{ board.registered_dttm }}</span>
                </li>
                    
            {% endfor %}
        </ul>
    {% endif %}
    {% if request.session.user %}
        <button><a href="{% url 'cfboard:board_create' pk %}">Write</a></button>
    {% endif %}
</body>
</html>

FirstPro/templates/cfboard/ori_cfboard_detail.html
<table>
    <ul>
        <li><span>제목 : </span><span>{{ board.title }}</span><span> 카테고리 : </span><span>{{ board.catename }}</span><span>   조회수 : {{ board.hits }}</span><span> 글쓴이 : </span><span>{{ board.writer }}</span><span> 작성일자 : </span><span>{{ board.registered_dttm }}</span></li>
        <li><span>내용 </span><span>{{ board.contents }}</span></li>
    </ul>

    <div class="row">
        {% if errors %}
          <ul>
            {% for error in errors %}
              <li><div class="alert alert-primary">{{ error }}</div></li>
            {% endfor %}
          </ul>
        {% endif %}
        {% if comments %}
        <h1>Comment List</h1>
        <ul>
            {% for comment in comments %}
                <li>
                    <span>{{ comment.contents }}</spam><span>   작성자 : {{ comment.user }}</span> 
                </li>
            {% endfor %}
        </ul>
        {% endif %}
        <h3>댓글 쓰기</h3>
        <form method="post" action="{% url 'cfboard:board_comment' pk id %}">
          {% csrf_token %}
          <div class="form-group row">
            <textarea class="form-control" name="contents" rows="7"></textarea>
          </div>
          <div class="form-group row float-right">
            <button type="submit" class="btn btn-primary">저장하기</button>
          </div>
        </form>
      </div>

    <button><a href="{% url 'cfboard:boards' pk %}">목록</a></button>
</table>

FirstPro/templates/cfboard/ori_cfboard_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Board List</h1>
    <ul>
        {% for board in object_list %}
            <li>
                <p>{{ board.title }}</p>
                <p>{{ board.contents }}</p>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

FirstPro/templates/cfboard/ori_cfboard_write.html
<div class="container">
  <div class="row">
    {% if errors %}
    <ul>
      {% for error in errors %}
      <li><div class="alert alert-primary" role="alert">{{ error }}</div></li>
      {% endfor %}
    </ul>
    {% endif %}
    <form method="post" action="{% url 'cfboard:board_create' pk %}" enctype="multipart/form-data" class="col-lg-8 col-md-10 mx-auto">
      {% csrf_token %}  
      <div class="form-group row">
        <label for="title">제목</label>
        <input type="text" class="form-control" name="title" placeholder="제목을 입력해주세요.">
      </div>
      <div class="form-group row">
        <label for="content">내용</label>
        <textarea class="form-control" name="content" rows="7"></textarea>
      </div>
      <div class="form-group row">
        <label for="category">카테고리</label>
        <select name="category">
          <option value="">카테고리</option>
          <option value="1">주문/결제</option>
          <option value="2">배송</option>
          <option value="3">제품문의</option>
          <option value="4">납품신청</option>
          <option value="5">회원신청</option>
          <option value="6">제품불량</option>
          <option value="7">기타</option>
        </select>
      </div>
      <div class="form-group row">
        <label for="disclosure">공개여부</label>
        <select name="disclosure">
          <option value="0">공개</option>
          <option value="1">비공개</option>
        </select>
      </div>
      <div class="form-group row float-right">
        <button type="submit" class="btn btn-primary">저장하기</button>
      </div>
    </form>
  </div>
</div>