FirstPro/CoffeeShop/urls.py
from django.contrib import admin
from django.urls import include
from django.conf.urls.static import static
from CoffeeShop import settings
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('cfuser.urls')),
    url(r'^board/', include('cfboard.urls')),
    url(r'^coffee/', include('cfproduct.urls')),
    url(r'^buy/', include('cfbuy.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FirstPro/cfbuy/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from cfbuy.views import *

app_name = 'cfbuy'

urlpatterns = [
    # url(r'^test/$',TemplateView.as_view(template_name='cfproduct/test.html'),name='test'),
    url(r'^detail/$',TemplateView.as_view(template_name='cfbuy/_detail.html'),name='detail'),
    url(r'^cart/$',TemplateView.as_view(template_name='cfbuy/cart.html'),name='cart'),
    url(r'^buy_page/$',TemplateView.as_view(template_name='cfbuy/buy_page.html'),name='buy_page'),
    url(r'^order/$',order_list,name='order_list'),
    url(r'^complete/$',buy_complete,name='buy_complete'),
    url(r'^graph/$',show_graph,name='graph'),
    url(r'^kakao/$',kakaopay,name='kakao_pay'),
    url(r'^approve/$',approval,name='approve'),
    url(r'^cancel/$',TemplateView.as_view(template_name='cfbuy/payCancel.html'),name='cancel'),
    url(r'^fail/$',TemplateView.as_view(template_name='cfbuy/payFail.html'),name='fail'),
]

FirstPro/cfproduct/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from cfproduct.views import *

app_name = 'cfproduct'

urlpatterns = [
    # url(r'^test/$',TemplateView.as_view(template_name='cfproduct/test.html'),name='test'),
    url(r'^$', index, name='index'),
    url(r'^(?P<pk>\d{1})/$',coffee, name='coffee'),
    url(r'^detail/(?P<id>\d{1,3})/$',product_detail, name='coffee_detail'),
    url(r'^detail/(?P<id>\d{1,3})/comment$',product_comment, name='coffee_comment'),
    url(r'^buy/detail/$',buy_detail, name='buy_detail'),
  
    url(r'^detail/$',TemplateView.as_view(template_name='cfproduct/product_detail.html'),name='detail'),
    url(r'^cart/$',TemplateView.as_view(template_name='cfproduct/cart.html'),name='cart'),
    url(r'^buy_page/$',TemplateView.as_view(template_name='cfproduct/buy_page.html'),name='buy_page'),
    url(r'^order/$',TemplateView.as_view(template_name='cfproduct/order.html'),name='order'),
]

FirstPro/cfuser/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from cfuser.views import *
from cfbuy.views import show_graph
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cfuser'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^graph/$', show_graph, name='graph'),
    url(r'^cart/$',cart,name='cart'),
    url(r'^about/$',TemplateView.as_view(template_name='map.html'),name='about'),
    url(r'^profile/$',profile,name='profile'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FirstPro/cfproduct/models.py
from django.db import models
from cfuser.models import Cfuser
from CoffeeShop.settings import MEDIA_ROOT
from django.db.models.expressions import Window
from django.db.models.functions import RowNumber
from django.db.models import F


# Create your models here.
# Create your models here.
class Coffeecode(models.Model):
    cfcode = models.CharField(max_length=50)
    
    def __str__(self):
        return self.cfcode
    
    class Meta:
        db_table = 'cfcode name'
        verbose_name = '커피 코드'
        verbose_name_plural = '커피 코드'

class Cfproduct(models.Model):
    name = models.CharField(max_length=50,verbose_name='이름')
    price = models.IntegerField(verbose_name='price')
    image = models.ImageField(blank=True, null=True, upload_to="images", default='default.jpg')
    cfcode = models.ForeignKey('cfproduct.Coffeecode', on_delete=models.CASCADE,verbose_name='커피종류')
    
    def __str__(self):
        return self.name

    class Meta:
        db_table = 'coffeeshop coffee'
        verbose_name = '커피'
        verbose_name_plural = '커피'

class Opcode(models.Model):
    title = models.CharField(max_length=30, verbose_name='옵션명')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'option title'
        verbose_name = '옵션코드'
        verbose_name_plural = '옵션코드'

class CftoOption(models.Model):
    coffee_id = models.ForeignKey('cfproduct.Cfproduct', on_delete=models.CASCADE,verbose_name='커피명')
    option_id = models.ForeignKey('cfproduct.Cfoption', on_delete=models.CASCADE,verbose_name='옵션')
    amount = models.IntegerField(verbose_name='추가금액', default=0)
    
    def __str__(self):
        return self.coffee_id.name +'(' + self.option_id.code_option.title + ' : ' + self.option_id.option + ')'

    class Meta:
        db_table = 'coffee to option'
        verbose_name = '커피_옵션'
        verbose_name_plural = '커피_옵션'

class Cfoption(models.Model):
    code_option = models.ForeignKey('cfproduct.Opcode', on_delete=models.CASCADE,verbose_name='옵션코드', default='')
    option = models.CharField(max_length=30, verbose_name='옵션', default='')
    

    def __str__(self):
        return self.code_option.title + " : " + self.option

    class Meta:
        db_table = 'coffee option'
        verbose_name = '옵션'
        verbose_name_plural = '옵션'

class Cfcomment(models.Model):
    coffee = models.ForeignKey('cfproduct.Cfproduct', on_delete=models.CASCADE,verbose_name='커피')
    user = models.ForeignKey('cfuser.Cfuser', on_delete=models.CASCADE, verbose_name='작성자')
    contents = models.TextField(verbose_name='내용')
    

    def __str__(self):
        return self.coffee.name + self.user.name
    
    class Meta:
        db_table = 'coffee comment'
        verbose_name = '댓글'
        verbose_name_plural = '댓글'

FirstPro/cfproduct/views.py
from django.shortcuts import render, reverse, redirect
from django.core.paginator import Paginator
import json

from cfproduct.models import *
from cfbuy.models import Cfselect, Basketdetail, Cfbuy
# Create your views here.

def index(request):
    return render(request, 'cfproduct/index.html', { 'email': request.session.get('user') })

def coffee(request, pk):
    res_data = {'pk' : pk}
    cfcode = Coffeecode.objects.get(id=pk)
    try:
        coffee_list = Cfproduct.objects.filter(cfcode=cfcode).order_by('id')
        res_data['cfcode'] = cfcode
        res_data['coffee_list'] = coffee_list
        paginator = Paginator(coffee_list, 6) # Show 6 contacts per page.
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        res_data['page_obj'] = page_obj
        
    except Cfproduct.DoesNotExist:
        raise Http404('게시글을 찾을 수 없습니다')

    return render(request, 'cfproduct/product.html', res_data)

def cfcreate(request):
    cfproduct = Cfproduct()
    cfproduct.name = request.POST['name']
    cfproduct.price = int(request.POST['price'])
    cfproduct.image = request.FILES['images']
    cfproduct.cfcode = Coffeecode.objects.get(id=1)
    cfproduct.save()
    return redirect(reverse('cfproduct:coffee', kwargs={'pk': 1}))

def product_detail(request,id):
    cfproduct = Cfproduct.objects.get(id=id)
    res_data = {'coffee' : cfproduct}
    res_data['id'] = id
    cftooptions = CftoOption.objects.filter(coffee_id=cfproduct)
    res_data['cftooptions'] = cftooptions
    comments = Cfcomment.objects.filter(coffee=cfproduct)
    comment = []
    for idx, c in enumerate(comments):
        comment.append([(idx+1)%2, c])
    res_data['comments'] = comment
    option_set = set()
    price_info = {}
    for cftooption in cftooptions:
        code_option = cftooption.option_id.code_option
        price_info[cftooption.id]=cftooption.amount
        option_set.add(code_option)
    price_info['len'] = len(option_set)
    price_info['base'] = cfproduct.price
    res_data['priceJson'] = json.dumps(price_info)
    res_data['option_set'] = option_set
    return render(request, 'cfproduct/product_detail.html',res_data)


def buy_detail(request):
    id = request.POST.get('id')
    res_data = {}
    if request.method == 'POST':
        cart_or_buy = request.POST.get('buy')
        cfproduct = Cfproduct.objects.get(id=id)
        res_data['coffee'] = cfproduct    
        options = (eval(str(request.POST.get('option'))))
        cftooptions = CftoOption.objects.filter(coffee_id=cfproduct)

        options_info_id = []
        options_info = []
        quan_dict = {}
        total_sum = 0
        if options:
            if cart_or_buy == 'buy':
                user = Cfuser.objects.get(email=request.session['user'])
                recent_buy = Cfbuy.objects.filter(buyer=user).order_by('-buy_date')
                if recent_buy:
                    recent_buy = recent_buy[0]
                res_data['recent_buy'] = recent_buy

                for k, v in options.items():
                    if len(v)>2:
                        options_info.append([])
                        options_info_id.append([])
                        option_list = []
                        option_list_id = []
                        for i in v[:-2]:
                            target = CftoOption.objects.get(id=i)
                            option_list.append(target)
                            option_list_id.append(i)
                        total_sum += v[-1]*v[-2]
                        options_info[-1].append({'option_list':option_list,'quantity':v[-2],'price':v[-1], 'sum':v[-2]*v[-1]})
                        options_info_id[-1].append({'option_list':option_list_id, 'quantity':v[-2]})
                if len(options_info):
                    res_data['total_sum'] = total_sum
                    res_data['cftooptions'] = cftooptions
                    res_data['options_info'] = options_info
                    res_data['options_info_id'] = options_info_id
                    res_data['quantitys'] = quan_dict
                    return render(request, 'cfbuy/buy_page.html', res_data)
            else: 
                user = Cfuser.objects.get(email=request.session['user'])
                for k, v in options.items():
                    basketdetail = Basketdetail()
                    basketdetail.buyer = user
                    basketdetail.save()
                    basketsum = 0
                    quantity = 0
                    if len(v)>2:
                        for i in v[:-2]:
                            target = CftoOption.objects.get(id=i)
                            cfselect = Cfselect()
                            cfselect.cfoption = CftoOption.objects.get(id=i)
                            cfselect.cf_code = cfselect.cfoption.coffee_id.cfcode
                            cfselect.basket = basketdetail
                            cfselect.save()
                    
                    basketdetail.quantity = v[-2]
                    basketdetail.amount = v[-1]
                    basketdetail.total = basketdetail.quantity * basketdetail.amount
                    basketdetail.save()
                
                return redirect(reverse('cfuser:cart'))
   
    return redirect(reverse('cfproduct:coffee_detail', kwargs={'id': id}))

 
def product_comment(request, id):
    errors = []
    if request.method == "POST":
        user = Cfuser.objects.get(email=request.session['user'])
        coffee = Cfproduct.objects.get(id=id)
        contents = request.POST.get('contents')

        if not contents:
            errors.append('댓글을 입력해주세요.')

        if not errors:
            comment = Cfcomment.objects.create(coffee=coffee, user=user, contents=contents)
            return redirect(reverse('cfproduct:coffee_detail', kwargs={'id' : id}))

    return redirect(reverse('cfproduct:coffee_detail', kwargs={'id' : id}))

FirstPro/templates/cfproduct/cfselect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Buy Page</h1>
    <img src="{{ coffee.image.url }}" width="300px" height="300px">
    <p><span>상품명 : </span><span>{{ coffee.name }}</span></p>
    <p><span>판매가 : </span><span>{{ coffee.price }}</span></p>
    <form method="post" action="{% url 'cfproduct:buy_detail' %}">
        {% csrf_token %}
        <input type="hidden" name="id" value="{{ coffee.id }}">
        {% for option_title in option_set %}
            <h3>{{ option_title }}</h3>
            <select name="{{ option_title }}">
            {% for option in option_list %}
                {%if option.code_option == option_title %}
                    <option value="{{ option.id }}">{{ option.option }}</option>
                {% endif %}
            {% endfor %}
            </select>
        {% endfor %}     
        <button type="submit" name="submit" value="buy">Buy now</button>
        <button type="submit" name="submit" value="cart">Cart</button>
    </form>

</body>
</html>

FirstPro/templates/cfproduct/coffee.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Coffee</h1>
    {% for coffee in coffee_list %}
    <li>
    {% if coffee.image %}
        <img src="{{ coffee.image.url }}" width="300px" height="300px">
        <p></p>
    {% endif %}
    <span><a href="{% url 'cfproduct:cfselect' coffee.id %}">{{ coffee.name }}</a></span><span>{{ coffee.price }}</span>
    </li>
    {% endfor %}
</body>
</html>

FirstPro/templates/cfproduct/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

FirstPro/templates/cfproduct/product.html
{% extends 'base.html' %}

{% load static %}

{% block contents %}
<style>
    .row{
        margin: 80px auto;
    }
    .price{
        color: white;
    }
    h3{
        margin-top: 60px;
        color: #e6a756;
        text-align: center;
    }
    h3 > a{
        text-decoration: none;
        color:#e6a756;
    }
    h3 > a:hover{
        color: #d3841c;
    }
    .add-to-cart{
        text-decoration: none;
        color: #e6a756;
    }
    .add-to-cart:hover{
        color: #d3841c;
    }
    .price{
        text-align: center;
        margin-bottom: 20px;
    }
    .pagination{
        margin: 0 auto;
      }
    span{
        color: #ce8f3d;
    }
    span > a{
        color: #ce8f3d;
    }

</style>
<div class="container ">
    <h3 class="h3"></h3>
    <div class="row center-block">
        {% for coffee in page_obj %}
                <div class="imgbox" style="width: 350px; margin: 0 auto;">
                    <div class="product-grid">
                    {% if coffee.image %}                    
                        <div class="product-image" width="300px" height="300px">
                                <img class="pic" src="{{ coffee.image.url }}" width="300px" height="300px">
                        </div>
                    {% endif %}
                        <div class="product-content">
                            <h3 class="title-1"><a href="{% url 'cfproduct:coffee_detail' coffee.id %}">{{ coffee.name }}</a></h3>
                            <div class="price">{{ coffee.price }}원</div>
                        </div>
                    </div>
                </div>
        {% endfor %}  
    </div>
</div>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}

FirstPro/templates/cfproduct/product_detail.html
{% extends 'base.html' %}

{% load static %}

{% block contents %}

<style>
    a{
        text-decoration: none;
    }
    .card{
        margin: 100px 0 50px 0;
    }
    .preview{
        background-color: white;
        text-align: center;
        border-top-left-radius: 8px;
        border-bottom-left-radius: 8px;
    }
    .tab-pane{
        margin-top: 50px;
    }
    li{
        list-style: none;
    }
    .count{
        width: 30px;
    }
    .action{
        margin: 30px 0 30px 0;
    }
    .action > .add-to-cart > a{
        text-decoration: none;
        color: #e0e0eb;
    }
    .action > .like > .fa > a{
        text-decoration: none;
        color: #fff;
    }
    .reply-form {
    opacity: 0.8;
    margin-top: 40px;
    padding: 37px;
    }

    .textInput {
        border-top-left-radius: 10px;
        border-bottom-left-radius: 10px;
        width: 40%;
        height: 45px;
        margin: 0 !important;
    }
    .textInput:focus {
        box-shadow: none;
        outline: none
    }
    .commentBox ul .profileBox {
        width: 70px;
        height: 70px;
        border-radius: 50%;
        display: inline-flex;
        justify-content: center;
        align-items: center;
        background-color: #002247;
        color: rgb(93, 95, 95);
        font-size: 25px;
        font-weight: 700;
    }
    .commentBox ul li:nth-child(even) .profileBox {
        background-color: #222;
    }
    .profileText {
        border-radius: 7px;
        padding: 10px;
        position: relative;
        background-color: #e0efff;
        display: inline-block;
        margin-left: 15px;
        width: 50%;
    }
    .profileText::before {
        content: '';
        position: absolute;
        left: -9px;
        top: 50%;
        transform: translateY(-50%);
        width: 0px;
        height: 0px;
        border-top: 10px solid transparent;
        border-bottom: 10px solid transparent;
        border-right: 10px solid #e0efff;
        z-index: 1;
    }
    .commentBox ul li {
        display: flex;
        align-items: center;
    }
    .commentBox ul li:nth-child(even) .profileText::before {
        left: unset;
        right: -9px;
        transform: translateY(-50%) rotate(175deg);
    }

    .commentBox ul li:nth-child(even) .profileText {
        text-align: left;
    }
    div#div_id_username {
        margin-top: 2%;
    }
    .commentBox ul li:nth-child(even) .profileText {
        margin-left: 0;
        margin-right: 15px
    }
    .commentBox ul li:nth-child(even) {
        text-align: right;
        margin: 20px 0;
        justify-content: flex-end;
    }
    .btn-comment{
        background-color: #e6a756;
    }
    .nav-item-sub{
        text-decoration: none;
        background-color: gray;
        color: white;
    }
    .nav-item-sub:hover{
        color: white;
    }

    

    

</style>

<div class="container">
    <div class="card">
        <div class="container-fliud">
            <div class="wrapper row">
                <div class="preview col-md-6">  
                    <div class="preview-pic tab-content">
                        {% if coffee.image %}
                            <div class="tab-pane active" id="pic-1"><img src="{{ coffee.image.url }}" width="300px" height="300px"></div>
                        {% endif %}                      
                    </div>        
                </div>             
                    <div class="details col-md-6">
                        <br>
                        <h3 class="product-title">{{ coffee.name }}</h3>
                        <h4 class="price">가격 : <span>{{ coffee.price }}원</span></h4>
                        
                            <li>
                            <hr/>
                            {% for option_title in option_set %}
                                <li style="padding-right: 30px;">
                                    <label>{{ option_title }} :</label>
                                    <select class="form-select form-select-sm" aria-label=".form-select-sm example" name="{{ option_title }}" onchange="handleOnChange(this)">
                                        {% for cftooption in cftooptions %}
                                            {%if cftooption.option_id.code_option == option_title %}
                                                <option value="{{ cftooption.id }}">{{ cftooption.option_id.option }}</option>
                                            {% endif %}
                                        {% endfor %}
                                    </select>
                                </li>
                                <hr/>
                            {% endfor %}
                            </li>
                            <form method="post" action="{% url 'cfproduct:buy_detail' %}" id="select_form">
                                {% csrf_token %}
                                <input type="hidden" name="id" value="{{ coffee.id }}">
                                <section id="options">
                                    
                                </section>
                                <hr/>
                                <br>
                                <section>
                                    <p id="price" style="text-align: right; padding-right:30px">최종합산 금액 : 0원</p>
                                </section>
                                <hr/>
                                <div class="action">
                                    {% if request.session.user %}
                                        <button class="add-to-cart btn btn-secondary" type="submit" name="buy" value="cart">장바구니 추가</button>
                                        <button class="like btn btn-primary" type="submit" name="buy" value="buy"><span class="fa fa-heart">구매하기</span></button>
                                    {% else %}
                                        <button class="add-to-cart btn btn-secondary" type="button" name="buy" value="cart"><a href="{% url 'cfuser:login' %}">장바구니</a></button>
                                        <button class="like btn btn-primary" type="button" name="buy" value="buy"><span class="fa fa-heart"><a href="{% url 'cfuser:login' %}">구매하기</a></span></button>
                                    {% endif %}
                                </div>
                            </form>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
      <div class="col-xs-12 ">
        <nav>
          <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
            <a class="nav-item-sub nav-link active" id="nav-review-tab" data-toggle="tab" href="#nav-review" role="tab" aria-controls="nav-review" aria-selected="true">구매후기</a>
            <a class="nav-item-sub nav-link" id="nav-detail-tab" data-toggle="tab" href="#nav-detail" role="tab" aria-controls="nav-detail" aria-selected="false">상세정보</a>
          </div>
        </nav>
        <div class="tab-content py-3 px-3 px-sm-0" id="nav-tabContent">
            <div class="col-md-12 tab-pane fade show active" id="nav-review" role="tabpanel" aria-labelledby="nav-review-tab">
                {% if comments %}
                    <div class="commentBox">
                        <ul class="list-unstyled">
                            {% for comment in comments %}
                            {% if comment.0 == 0 %} 
                                <li><span class="profileText">{{ comment.1.contents }}</span><span class="profileBox" style="background: no-repeat center/140% url('{{ comment.user.image.url }}');">{{ comment.1.user }}</span></li>
                            {% else %}
                                <li><span class="profileBox" style="background: no-repeat center/140% url('{{ comment.user.image.url }}');">{{ comment.1.user }}</span><span class="profileText">{{ comment.1.contents }}</span></li>
                            {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% if request.session.user %}
                <form class="reply-form tab-pane col-md-12" method="post" action="{% url 'cfproduct:coffee_comment' id %}">
                    {% csrf_token %}
                    <div id="div_id_username" class="form-group required">
                        <div class="controls form-group d-flex">
                            <input class="input-md  textinput textInput form-control" id="id_username" name=contents placeholder="Write your review" type="text" />
                            <button type="submit" class="btn-comment btn border-radius-0">POST</button>
                        </div>
                    </div>
                </form>
                {% endif %}
            </div>
            <div class="tab-pane fade" id="nav-detail" role="tabpanel" aria-labelledby="nav-detail-tab">
                Et et consectetur ipsum labore excepteur est proident excepteur ad velit occaecat qui minim occaecat veniam. Fugiat veniam incididunt anim aliqua enim pariatur veniam sunt est aute sit dolor anim. Velit non irure adipisicing aliqua ullamco irure incididunt irure non esse consectetur nostrud minim non minim occaecat. Amet duis do nisi duis veniam non est eiusmod tempor incididunt tempor dolor ipsum in qui sit. Exercitation mollit sit culpa nisi culpa non adipisicing reprehenderit do dolore. Duis reprehenderit occaecat anim ullamco ad duis occaecat ex.
            </div>
        </div>
      
      </div>
    </div>
</div>
</div>
</div>




<script>
    var total_sum = 0;
    var options = {};
    var cnt = 0;
    var param = {};
    var price_info = JSON.parse("{{ priceJson|escapejs }}");
    var selector = document.querySelectorAll(".form-select")
    function update_form(){
        var test = JSON.stringify(param)
        var el = document.createElement("input");
        el.type = "hidden";
        el.name = "option";
        el.value = test;
        document.getElementById('select_form').appendChild(el)
        console.log(test);
        document.getElementById('price').innerText = "최종합산 금액 : "+total_sum+"원 ";
    }

    function setBtn(num){
        $('#option'+num+' > .__count_range input[count_range]').click(function(e){
            e.preventDefault();
            var type = $(this).attr('count_range');
            var $count = $(this).parent().children('input.count');
            var count_val = $count.val(); // min 1
            var arr = param[num];
            if(type=='m'){
                if(count_val<=1){
                    return;
                }
            $count.val(parseInt(count_val)-1);
            total_sum -= arr[arr.length-1]
            arr[arr.length-2]--;
            }else if(type=='p'){
                $count.val(parseInt(count_val)+1);
                total_sum += arr[arr.length-1]
                arr[arr.length-2]++;
            }
            update_form();
        });
    }; 
    
    function remove_div(num){
        document.getElementById('option'+num).remove()
        var arr = param[num];
        total_sum -= arr[arr.length-1]*arr[arr.length-2];
        param[num] = [];
        update_form();
        console.log(param)
    }

    function add_option(){
        var div = document.createElement('div');
        div.setAttribute("id", "option"+cnt);
        div.innerHTML = `<div class="__count_range text-right"> 
                <span class= "text-left" id='result`+cnt+`'></span>
                <span onclick="remove_div(`+cnt+`)" style="cursor: pointer;"><img src="{% static 'img/cancel.png' %}" width=35px;></span>
                <input value="-" count_range="m" type="button">
                <input class="count" value="1" readonly="" name="quantity">
                <input value="+" count_range="p" type="button">
                </div> `
        document.getElementById('options').appendChild(div);
        setBtn(cnt);
    }
    function handleOnChange(e){
        var sum = price_info['base'];
        if(e.selectedIndex != 0){
            options[e.options[0].text] = e.options[e.selectedIndex].text          
        }
        if(Object.keys(options).length == price_info['len']){
            var option_arr = []
            var text = "{ ";
            for(option in options){
                text += option + " : " + options[option]+" ";
            }
            text += "}";
            for(var i=0;i<selector.length;i++)
            {
                sum += price_info[selector[i].options[selector[i].selectedIndex].value];
                option_arr.push(selector[i].options[selector[i].selectedIndex].value);
                selector[i].selectedIndex=0;                
            }
            cnt++;
            option_arr.push(1);
            option_arr.push(sum);
            total_sum += sum;
            param[cnt]=option_arr;
            options={};            
            console.log(sum);
            add_option();
            update_form();
            document.getElementById('result'+cnt).innerText = text;            
        }        
    };
    $(document).ready(function(){
        var pro_elements = document.querySelectorAll('li > .profileBox');
        var com_elements = document.querySelectorAll('li > .profileText');
        for(var elem in pro_elements){
            var str = pro_elements[elem].innerText
            str = str.substring(0,1);
            pro_elements[elem].innerText = str;
            str = com_elements[elem].innerText + ' (' + str + '**)';
            com_elements[elem].innerText = str;
        }
    });




    


</script>
{% endblock %}