FirstPro/CoffeeShop/urls.py
from django.contrib import admin
from django.urls import include
from django.conf.urls.static import static
from CoffeeShop import settings
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('cfuser.urls')),
    url(r'^board/', include('cfboard.urls')),
    url(r'^coffee/', include('cfproduct.urls')),
    url(r'^buy/', include('cfbuy.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FirstPro/cfbuy/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from cfbuy.views import *

app_name = 'cfbuy'

urlpatterns = [
    # url(r'^test/$',TemplateView.as_view(template_name='cfproduct/test.html'),name='test'),
    url(r'^detail/$',TemplateView.as_view(template_name='cfbuy/_detail.html'),name='detail'),
    url(r'^cart/$',TemplateView.as_view(template_name='cfbuy/cart.html'),name='cart'),
    url(r'^buy_page/$',TemplateView.as_view(template_name='cfbuy/buy_page.html'),name='buy_page'),
    url(r'^order/$',order_list,name='order_list'),
    url(r'^complete/$',buy_complete,name='buy_complete'),
    url(r'^graph/$',show_graph,name='graph'),
    url(r'^kakao/$',kakaopay,name='kakao_pay'),
    url(r'^approve/$',approval,name='approve'),
    url(r'^cancel/$',TemplateView.as_view(template_name='cfbuy/payCancel.html'),name='cancel'),
    url(r'^fail/$',TemplateView.as_view(template_name='cfbuy/payFail.html'),name='fail'),
]

FirstPro/cfproduct/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from cfproduct.views import *

app_name = 'cfproduct'

urlpatterns = [
    # url(r'^test/$',TemplateView.as_view(template_name='cfproduct/test.html'),name='test'),
    url(r'^$', index, name='index'),
    url(r'^(?P<pk>\d{1})/$',coffee, name='coffee'),
    url(r'^detail/(?P<id>\d{1,3})/$',product_detail, name='coffee_detail'),
    url(r'^detail/(?P<id>\d{1,3})/comment$',product_comment, name='coffee_comment'),
    url(r'^buy/detail/$',buy_detail, name='buy_detail'),
  
    url(r'^detail/$',TemplateView.as_view(template_name='cfproduct/product_detail.html'),name='detail'),
    url(r'^cart/$',TemplateView.as_view(template_name='cfproduct/cart.html'),name='cart'),
    url(r'^buy_page/$',TemplateView.as_view(template_name='cfproduct/buy_page.html'),name='buy_page'),
    url(r'^order/$',TemplateView.as_view(template_name='cfproduct/order.html'),name='order'),
]

FirstPro/cfuser/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from cfuser.views import *
from cfbuy.views import show_graph
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cfuser'

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^graph/$', show_graph, name='graph'),
    url(r'^cart/$',cart,name='cart'),
    url(r'^about/$',TemplateView.as_view(template_name='map.html'),name='about'),
    url(r'^profile/$',profile,name='profile'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FirstPro/cfbuy/models.py
from django.db import models
from django.utils.timezone import now
from cfuser.models import Cfuser
from cfproduct.models import Cfproduct, Coffeecode
# Create your models here.

BUY_CHOICES = (
    (0, 'credit'),
    (1, 'cash'),
    (2, 'kakaopay')
)

class Cfbuy(models.Model):
    buyer = models.ForeignKey('cfuser.Cfuser', on_delete=models.CASCADE,verbose_name='구매자')
    recipient = models.CharField(max_length=20, verbose_name='수령인', default='')
    postcode = models.CharField(max_length=20,verbose_name='우편번호', default='')
    address = models.CharField(max_length=50,verbose_name='주소', default='')
    extraAddress = models.CharField(max_length=50,verbose_name='참고항목',blank='true', null='true')
    detailAddress = models.CharField(max_length=50,verbose_name='상세주소', default='')
    buy_method = models.SmallIntegerField(choices=BUY_CHOICES)
    phone = models.CharField(max_length=20, verbose_name='전화번호', default='')
    phone1 = models.CharField(max_length=20, verbose_name='전화번호1', default='')
    phone2 = models.CharField(max_length=20, verbose_name='전화번호2', default='')
    phone3 = models.CharField(max_length=20, verbose_name='전화번호3', default='')
    email = models.CharField(max_length=50, verbose_name='email', default='')
    email_name = models.CharField(max_length=20, verbose_name='이메일이름', default='')
    email_domain = models.CharField(max_length=20, verbose_name='이메일도메인', default='')
    delivery_msg = models.CharField(max_length=100, verbose_name='delivery_msg', default='',blank='true', null='true')
    buy_date = models.DateTimeField(default=now, verbose_name='구매일자')

    def __str__(self):
        return "Buy Info No."+str(self.id)+" "+self.buyer.name
    
    class Meta:
        db_table = 'buyer info'
        verbose_name = '구매'
        verbose_name_plural = '구매'

class Buydetail(models.Model):
    buy_info = models.ForeignKey('cfbuy.Cfbuy', on_delete=models.CASCADE,verbose_name='구매정보')
    amount = models.IntegerField(default=0, verbose_name='주문 총 금액')
    quantity = models.IntegerField(verbose_name='수량', default=1)

    def __str__(self):
        return "Buy Detail No."+str(self.buy_info.id)+"_"+str(self.id)
    
    class Meta:
        db_table = 'buyer detail'
        verbose_name = '구매상세'
        verbose_name_plural = '구매상세'

class Basketdetail(models.Model):
    buyer = models.ForeignKey('cfuser.Cfuser', on_delete=models.CASCADE,verbose_name='구매자')
    amount = models.IntegerField(default=0, verbose_name='금액')
    total = models.IntegerField(default=0, verbose_name='총금액')
    quantity = models.IntegerField(verbose_name='수량', default=1)

    def __str__(self):
        return "Basket Detail No."+"_"+str(self.id)
    
    class Meta:
        db_table = 'basket detail'
        verbose_name = '장바구니상세'
        verbose_name_plural = '장바구니상세'

class Cfselect(models.Model):
    cfoption = models.ForeignKey('cfproduct.CftoOption', on_delete=models.CASCADE,verbose_name='구매제품')
    buy = models.ForeignKey('cfbuy.Buydetail', on_delete=models.CASCADE,verbose_name='구매내역', blank=True, null=True)
    basket = models.ForeignKey('cfbuy.Basketdetail', on_delete=models.CASCADE,verbose_name='장바구니내역', blank=True, null=True)
    cf_code = models.ForeignKey('cfproduct.Coffeecode', on_delete=models.CASCADE,verbose_name='커피코드', null=True)
    buy_date = models.DateTimeField(default=now, verbose_name='구매일자')

    def __str__(self):
        return str(self.id)

    class Meta:
        db_table = 'coffee select'
        verbose_name = '구매제품'
        verbose_name_plural = '구매제품'

FirstPro/cfbuy/views.py
import json, requests
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta

from django.shortcuts import render, redirect, reverse
from django.db.models import Q

from cfbuy.models import *
from cfproduct.models import CftoOption
from cfuser.models import Cfuser

buy_id_list = []
basket_id_list = []

# Create your views here.
def buy_complete(request):
    baskets = request.POST.get('baskets')
    if baskets:
        baskets = eval(baskets)
        for b in baskets:
            basket_id_list.append(b)


    cfbuy = Cfbuy()
    cfbuy.buyer = Cfuser.objects.get(email=request.session['user'])
    cfbuy.recipient = request.POST.get('recipient')
    cfbuy.postcode = request.POST.get('postcode')
    cfbuy.address = request.POST.get('address')
    cfbuy.detailAddress = request.POST.get('detailAddress')
    cfbuy.extraAddress = request.POST.get('extraAddress')
    cfbuy.phone1 = request.POST.get('phone1')
    cfbuy.phone2 = request.POST.get('phone2')
    cfbuy.phone3 = request.POST.get('phone3')
    cfbuy.phone = request.POST.get('phone1') + request.POST.get('phone2') + request.POST.get('phone3')
    cfbuy.email_name = request.POST.get('email')
    cfbuy.email_domain = request.POST.get('domain')
    cfbuy.email = request.POST.get('email')+ '@' + request.POST.get('domain')
    cfbuy.buy_method = request.POST.get('buy_method')
    cfbuy.delivery_msg = request.POST.get('deliverymsg')
    cfbuy.save()
    buy_id_list.append(cfbuy.id)

    options = eval(request.POST.get('options'))
    
    for option in options:
        buysum = 0
        price = 0
        buydetail = Buydetail()
        buydetail.buy_info = cfbuy
        buydetail.quantity = option[0]['quantity']
        buydetail.save()
        for ol in option[0]['option_list']:
            cfselect = Cfselect()            
            cfselect.cfoption = CftoOption.objects.get(id=ol)
            price = cfselect.cfoption.coffee_id.price
            cfselect.cf_code = cfselect.cfoption.coffee_id.cfcode
            cfselect.buy = buydetail
            
            buysum += buydetail.quantity * cfselect.cfoption.amount
            cfselect.save()
        
        buydetail.amount = buysum + buydetail.quantity * price
        buydetail.save()
    
    return redirect(reverse('cfbuy:kakao_pay'))
    
    # return redirect(reverse('cfbuy:order_list'))

def order_list(request):
    res_data={}
    user = Cfuser.objects.get(email=request.session['user'])
    orders = None
    print(request.POST)
    if request.method == "POST" and request.POST.get('search')!='reset':
        startdate = request.POST.get('start_date')
        enddate = request.POST.get('end_date')
        if startdate and enddate:
            orders = Cfbuy.objects.filter(buyer=user).filter(buy_date__range=[startdate, enddate]).order_by('-buy_date')
    else :
        enddate = datetime.today()
        startdate = enddate - relativedelta(months=3)
        orders = Cfbuy.objects.filter(buyer=user).filter(buy_date__range=[startdate, enddate]).order_by('-buy_date')

    res_data['order_list'] = []
    if orders:
        for order in orders:
            buydetails = Buydetail.objects.filter(buy_info=order)
            cfselects = []
            for buydetail in buydetails:
                cfselect = Cfselect.objects.filter(buy=buydetail)
                cfselects.append(cfselect)
            res_data['order_list'].append([order, cfselects, buydetails])
    return render(request, 'cfbuy/cfbuy_list.html', res_data)

def show_graph(request):
    year = datetime.today().year
    month = datetime.today().month
    res_data = {}
    sold_cf = {}
    names = {}
    cf_codes = Coffeecode.objects.all()
    for cf_code in cf_codes:
        cf_names = Cfproduct.objects.filter(cfcode=cf_code)
        

        for cf_name in cf_names:
            if names.get(cf_code.cfcode):
                names[cf_code.cfcode].append(cf_name.name)
            else:
                names[cf_code.cfcode] = [cf_name.name]
        
        sold_cf[cf_code.cfcode] = {}
        for m in range(0,6):
            nm = month - m
            ny = year
            if nm < 1:
                nm = nm + 12
                ny -= 1
            buydetails = set()
            year_month = str(ny)+'-'+str(nm)
            sold_cf[cf_code.cfcode][year_month] = {}
            
            for cf_name in cf_names:
                sold_cf[cf_code.cfcode][year_month][cf_name.name]=0
            cfselects = Cfselect.objects.filter(cf_code=cf_code).filter(~Q(buy__isnull=True)).filter(buy_date__year=ny).filter(buy_date__month=nm)
            for cfselect in cfselects:
                buydetails.add((cfselect.cfoption.coffee_id.name,cfselect.buy))
            for buydetail in buydetails:
                sold_cf[cf_code.cfcode][year_month][buydetail[0]] += buydetail[1].quantity

    res_data['sold_cf']=json.dumps(sold_cf)
    res_data['names']=json.dumps(names)
    return render(request, 'graph.html', res_data)

def kakaopay(request):
    buy_info = Cfbuy.objects.get(id=buy_id_list[0])
    buy_details = Buydetail.objects.filter(buy_info=buy_info)
    options = []
    buysum = 0
    
    name = ''
    names = set()
    total_quantity = 0
    quantity = []
    for buy_detail in buy_details:
        quantity.append(buy_detail.quantity)
        total_quantity += quantity[-1]
        options.append(Cfselect.objects.filter(buy=buy_detail))
    
    email = request.session['user']
    
    for idx, option in enumerate(options):
        price = 0
        names.add(option[0].cfoption.coffee_id.name)
        for ol in option:
            price = ol.cfoption.coffee_id.price  
            buysum += quantity[idx] * ol.cfoption.amount
        buysum = buysum + quantity[idx] * price
    
    for n in names:
        name += '[ '+ n + ' ]' + ' / '
    name = name[:-2]
    
    _admin_key = '6f1fe2f59f109a08501d463674bb96d7'
    _url = f'https://kapi.kakao.com/v1/payment/ready'
    _headers = {
        'Authorization': f'KakaoAK {_admin_key}',
    }
    _data = {
        'cid': 'TC0ONETIME',
        'partner_order_id': str(buy_id_list[0]),
        'partner_user_id': email,
        'item_name': name,
        'quantity': total_quantity,
        'total_amount': buysum,
        'tax_free_amount':'0',
        # 내 애플리케이션 -> 앱설정 / 플랫폼 - WEB 사이트 도메인에 등록된 정보만 가능합니다
        # * 등록 : http://IP:8000 
        # 'approval_url': reverse('cfbuy:approve'),
        'approval_url': 'http://127.0.0.1:8000/buy/approve',
        'fail_url':'http://127.0.0.1:8000/payFail',
        'cancel_url':'http://127.0.0.1:8000/payCancel'
    }
    _res = requests.post(_url, data=_data, headers=_headers)
    _result = _res.json()
    request.session['tid'] = _result['tid']
    return redirect(_result['next_redirect_pc_url'])
    # request.session['tid'] = res.json()['tid']      # 결제 승인시 사용할 tid를 세션에 저장
    # next_url = res.json()['next_redirect_pc_url']   # 결제 페이지로 넘어갈 url을 저장
    # return redirect(next_url)

    return render(request, 'cfbuy/kakao_pay.html')

def approval(request):
    email = request.session['user']
    _admin_key = '6f1fe2f59f109a08501d463674bb96d7'
    _url = 'https://kapi.kakao.com/v1/payment/approve'
    _headers = {
        'Authorization': f'KakaoAK {_admin_key}'
    }
    _data = {
        'cid':'TC0ONETIME',
        'tid': request.session['tid'],
        'partner_order_id': str(buy_id_list[0]),
        'partner_user_id':  email,
        'pg_token': request.GET['pg_token']
    }
    _res = requests.post(_url, data=_data, headers=_headers)
    _result = _res.json()
    context = {
        'res': _result,
    }
    if _result.get('msg'):
        cfbuy = Cfbuy.objects.get(id=buy_id_list[0])
        cfbuy.delete()
        buy_id_list.clear()
        basket_id_list.clear()
        return redirect('/')
    else:
        for b in basket_id_list:
            basketdetail = Basketdetail.objects.get(id=b)
            basketdetail.delete()
        basket_id_list.clear()
        buy_id_list.clear()
        return render(request, 'cfbuy/approval.html', context)

FirstPro/templates/cfbuy/approval.html
{% extends 'base.html' %}
{% block header %}
<script>
  $(document).ready(function(){
      var elem = document.getElementById('name');
      var str = elem.innerHTML.split('/').join('<br/>');
      elem.innerHTML = str;
      
  });
</script>
{% endblock %}

{% block contents %}

<style>
  h2{
    color: rgb(226, 176, 48);
  }
  .pay-frame{
    margin-bottom: 50px;
  }

</style>

  <div class="pay-frame mt-5 pt-5 row justify-content-center">
    <h2 class="text-center my-5 col-12">결제가 완료되었습니다!</h2>
    <div class="col-4 p-5 bg-light">
      <h3 class="text-center my-5">주문자 정보</h3>
      <div>
        <div class="my-3 row"><div class="h5 col-6">주문번호</div><div class="h6 col-6 text-right">{{ res.partner_order_id }}</div></div>
        <div class="my-3 row"><div class="h5 col-6">주문자 아이디</div><div class="h6 col-6 text-right">{{ res.partner_user_id }}</div></div>
        <div class="my-3 row"><div class="h5 col-6">상품명</div><div class="h6 col-6 text-right" id='name'>{{ res.item_name }}</div></div>
        <div class="my-3 row"><div class="h5 col-6">결제금액</div><div class="h6 col-6 text-right">{{ res.amount.total }}원</div></div>
        <div class="my-3 row"><div class="h5 col-6">결제승인시각</div><div class="h6 col-6 text-right">{{ res.approved_at }}</div></div>
      </div>
      <div class="mt-5 pt-3 text-center">
        <a href="{% url 'cfbuy:order_list' %}" class="btn btn-primary">목록으로 돌아가기</a>
        <a href="{% url 'cfuser:index' %}" class="btn btn-warning">메인으로 돌아가기</a>
      </div>

    </div>

  </div>

{% endblock %}

FirstPro/templates/cfbuy/buydetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>buy detail</h1>
    <img src="{{ coffee.image.url }}" width="300px" height="300px">
    <br/>
    <span><a href="{% url 'cfproduct:coffee_detail' coffee.id %}">{{ coffee.name }}</a></span>
    
    <span>{
        {% for select in select_list %}
            <span>{{ select.cfoption.option_id }} </span>
        {% endfor %}
    }</span>

    <span>{{ quantity }}개</span>
    <button><a href="#">결제하기</a></button>
</body>
</html>

FirstPro/templates/cfbuy/cart.html
{% extends 'base.html' %}

{% block contents %}
<style>
    div.mainbody{
        margin: 80px 0 60px 0;
        background-color: #f5f5f0;
        font-size: 13pt;
        min-width: 1100px;
        width: 100%;
        padding: 50px 0;
    }
    #frame{
        width: 80%;
        margin: 0 auto;
        padding: 50px 50px;
        background-color: #fff;
    }

    #frame2{
        border-bottom: solid 1px #e0e0eb;
        padding-bottom: 10px;
    }
    .home{
        float: right;
        clear: both;
    }
    table.calculation1{
        clear: both;
        border: solid 1px #e0e0eb;
        border-collapse: collapse;
        background-color: #f5f5f0;
        width: 100%;
        font-size: 10pt;
    }
    table.calculation1 th{
        border: solid 1px #e0e0eb;
        padding: 10px 0;
        text-align: center;
    }
    table.calculation1 td{
        border: solid 1px #e0e0eb;
        text-align: center;
    }

    table.calculation2{
        border: solid 1px #e0e0eb;
        border-collapse: collapse;
        background-color: #f5f5f0;
        width: 100%;
        font-size: 10pt;
    }

    table.calculation2 th{
        border: solid 1px #e0e0eb;
        text-align: center;
    }

    table.calculation2 td{
        border: solid 1px #e0e0eb;
        text-align: center;
    }

    .price{
        font-size: 20pt;
        font-weight: bold;
    }
    .btn{
        border: none;
        color: white;
        padding: 5px 10px;
        font-size: 13px;
        cursor: pointer;
        border-radius: 5px;
    }
    .backBtn{
        background: #fff;
        border: solid 1px gray;
    }
    .footerbtn{
        float: right;
        font-weight: bolder;
        font-size: 12pt;
        border-radius: 3px;
    }
    #allProduct, #productclear, #footerbtn{
        padding: 11px 25px;
    }
    #allProduct{
        background-color: #264d73;
        color: #fff;
        font-weight: bold;
        font-size: 12pt;
    }
    #productClear{
        background-color: gray;
        color: #fff;
        font-weight: bold;
        font-size: 12pt;
    }
    .aa:hover{
        cursor: pointer;
    }
</style>
<script>
    
    $(document).ready(function(){

        $("#notproduct").hide();

            $(".calculation1 thead input:checkbox[id=check]").click(function(){
            var bool = $(this).prop("checked");
                $(".calculation1 tbody input:checkbox[name=checkbox]").prop("checked", bool);
        });  
    });
</script>
<div class="mainbody">
    <div id="frame">
        <form>
            <div id="frame2">
                <span style="font-size: 16pt; font-weight: bold;">장바구니</span>
                <span class="home">홈 > 장바구니</span>
                <span></span> 
            </div>
            <br/>

            <div>
                <table class="calculation1">
                    <tr>
                        <th class="buy">상품목록</th>

                    </tr>
                </table>
            </div>
        </form>
        <br/>

        <div>
            <table class="calculation1">
                <thead>
                    <tr>
                        <th colspan="10" style="text-align: left; padding-left: 10px;">일반상품({{ baskets|length }})</th>
                    </tr>
                    <tr>
                        <th><input type="checkbox" name="checkbox" id="check" /></th>
                        <th><span>이미지</span></th>
                        <th style="width: 250px;"><span>상품정보</span></th>
                        <th>판매가</th>
                        <th>수량</th>
                        <th>합계</th>
                    </tr>
                </thead>
                <form method="POST">
                    {% csrf_token %}
                    <tbody id="calculation1tbody">
                        {% for basket in baskets %}
                                <tr id="calculation1_tr1" style="height: 90px; background-color: #fff;">
                                    <td><input type="checkbox" name="checkbox" id="check" value="{{ basket.0.id }}" /></td>
                                    {% if basket.1.0.cfoption.coffee_id.image %}
                                        <td style="border-left: none; border-right:none;"><img style="width: 70px; height: 70px;" src="{{ basket.1.0.cfoption.coffee_id.image.url }}"></td>
                                    {% endif %}
                                    <td style="text-align: left; padding-left: 10px; border-left: none; font-weight: bold;">
                                        <p>{{ basket.1.0.cfoption.coffee_id.name }}</p>
                                        <span>{</span>
                                            {% for options in basket.1 %}
                                                <span style="font-size:small;">{{ options.cfoption.option_id }}</span>
                                            {% endfor %}
                                        <span>}</span>
                                    </td>
                                    <td>
                                        {{ basket.0.amount }}
                                    </td>
                                    <td>
                                        {{ basket.0.quantity }}
                                    </td>
                                    <td>
                                        {{ basket.0.total }}
                                    </td>
                                </tr>
                            {% endfor %}                    
                    </tbody>
                
                    <tfoot>
                        <tr style="height: 60px;">
                            <td colspan="4" style="border-right: none; text-align:left; padding-left:10px;">
                                <span>[현재 장바구니에 추가하신 상품입니다.]</span>
                            </td>
                        </tr>
                    </tfoot>
                </table>
                <div style="margin: 10px 0;">
                    <span style="margin: 0 10px;" class="btnfloat">선택상품을</span>
                    <button type="submit" class="btn default btndelete" id="choiceProductDelete" name="btn" value="delete" style="background-color: gray; color:#fff">삭제하기</button>&nbsp;
                    <span class="clearboth"></span>
                </div>
                <br/><br/>
                <br/><br/>

                <div align="center">
                    <button type="submit" class="btn default" name="btn" value="allbuy" id="allProduct">전체상품주문</button>
                    <button type="submit" class="btn default backBtn" name="btn" value="selectbuy" id="productClear">선택상품주문</button>

                    <span class="clearboth"></span>
                </div>
            </form>
            <br/><br/><br/><br/><br/>
            </div>
        </div>
    </div>
</div>


{% endblock %}

FirstPro/templates/cfbuy/graph.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Graph</h1>
    {% for detail in sold_cf.items %}
        <p>{{ detail.0 }} : {{ detail.1 }}</p>
    {% endfor %}
</body>
</html>

FirstPro/templates/cfbuy/kakao_pay.html
{% extends 'base.html' %}
{% block contents %}
  <div class="row mt-5">
    <h1 class="col-12 text-center my-5">KAKAO PAY</h1>
    <form method="post" class="col-12 text-center">
      {% csrf_token %}
      <button class="btn btn-warning">카카오페이로 결제하기</button>
    </form>
  </div>
{% endblock %}

FirstPro/templates/cfbuy/payCancel.html
{% extends 'base.html' %}
{% block contents %}


<style>
  h2{
    color: rgb(226, 176, 48);
  }
  .pay-frame{
    margin-bottom: 50px;
  }

</style>

  <div class="pay-frame mt-5 pt-5 row justify-content-center">
    <h2 class="text-center my-5 col-12">결제를 취소했습니다.</h2>
    <div class="col-4 p-5 bg-light">
      <h3 class="text-center my-5">취소완료</h3>
      <div class="mt-5 pt-3 text-center">
        <a href="{% url 'cfbuy:order_list' %}" class="btn btn-primary">목록으로 돌아가기</a>
        <a href="{% url 'cfuser:index' %}" class="btn btn-warning">메인으로 돌아가기</a>
      </div>

    </div>

  </div>

{% endblock %}

FirstPro/templates/cfbuy/payFail.html
{% extends 'base.html' %}
{% block contents %}

<script>
  $(document).ready(function(){
    var elem = document.getElementById("info-text");
    var timer = 2;
    setInterval(function(){
      elem.innerText = timer+"초 후 이전 페이지로 이동합니다.";
      console.log(timer)
      timer--;
      if (timer < 0){
        alert("이전 페이지로 이동합니다.");
        location.href = "{% url 'cfbuy:cart' %}";
      }
    }, 1000);
  });
   

</script>

<style>
  h2{
    color: rgb(226, 176, 48);
  }
  .pay-frame{
    margin-bottom: 50px;
  }

</style>

  <div class="pay-frame mt-5 pt-5 row justify-content-center">
    <h2 class="text-center my-5 col-12">결제를 실패했습니다.</h2>
    <div class="col-4 p-5 bg-light">
      <h3 class="text-center my-5" id="info-text">3초 후 이전 페이지로 이동합니다.</h3>
    </div>

  </div>

{% endblock %}